### PR TITLE
Ignore .vscode folder

### PR DESCRIPTION
**Pull request by lucasgomide**

### CODE REVIEW

**Comment by fidelisrafael** [comment]
The thing it is: this ".launch.json" is "a hand on the wheel"(HSUAHSUAHSA) for people using VS Code to Debug. The shortcut to test the current file is really useful. Let's say you want to test just the current file you're editing(and do not run the entire test suite)...with this `launch.json` config you can put `debugger` statements to debug your code, whereas you cannot do using `npm test [file]` because by what I know(and for what I tested) `jest` will ignore them.(probably they override `debugger` as a function that does nothing? I don't know).
What do you think? @lucasgomide

**Comment by lucasgomide** [comment]
@fidelisrafael I got your point. I agree that this makes easier debugging. But... there are more than 1000 IDEs and each one has a different configuration type, standard and format. 
How you will handler if each contributor add on this project their IDE's files configuration? Once given the same argument.

Again, I agree with you. That's an important point.. although I'd like to discuss it more.

**Comment by fidelisrafael** [comment]
I understand your point @lucasgomide, but it's not the case in this project...maybe at some point this will be a problem, but for now I will leave this configuration in the project since it's a **PAIN IN THE ASS** to debug javascript applications and this help a lot. I will introduce specific instructions at README about how to use VSCode to debug this project, I just realized and promoted "VSCode"  as the default debugger for this project....so if people want to create others configurations for their IDE's, they must do it by themselves.

As you probably know, VSCode is perfect for debugging, it's lovely ;)

**Comment by lucasgomide** [comment]
No problems dude.

I appreciate your point, txs ;)

I gonna close this PR

**Pull request closed without merging**
